In [25]:
import os
import sys
import pandas as pd
import logging
sys.path.append(os.path.abspath('../Scripts'))
import warnings
warnings.filterwarnings('ignore')

In [17]:
import feature as ft
import Eda as ed

In [34]:
df = 'merged_ecommerce_data.csv'
df = ed.load_data(df)

2024-10-30 09:20:53,963 - INFO - Attempting to load data from merged_ecommerce_data.csv
2024-10-30 09:20:54,953 - INFO - Successfully loaded data from merged_ecommerce_data.csv

In [35]:
df

,user_id,signup_time,purchase_time,purchase_value,device_id,source,browser,sex,age,ip_address,class,lower_bound_ip_address,upper_bound_ip_address,country
0,247547,2015-06-28 03:00:34,2015-08-09 03:57:29,47,KIXYSVCHIPQBR,SEO,Safari,F,30,16778864,0,1.677824e+07,1.677926e+07,Australia
1,220737,2015-01-28 14:21:11,2015-02-11 20:28:28,15,PKYOWQKWGJNJI,SEO,Chrome,F,34,16842045,0,1.680998e+07,1.684275e+07,Thailand
2,390400,2015-03-19 20:49:09,2015-04-11 23:41:23,44,LVCSXLISZHVUO,Ads,IE,M,29,16843656,0,1.684326e+07,1.684378e+07,China
3,69592,2015-02-24 06:11:57,2015-05-23 16:40:14,55,UHAUHNXXUADJE,Direct,Chrome,F,30,16938732,0,1.692467e+07,1.694106e+07,China
4,174987,2015-07-07 12:58:11,2015-11-03 04:04:30,51,XPGPMOHIDRMGE,SEO,Chrome,F,37,16971984,0,1.694106e+07,1.697382e+07,Thailand
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129141,33024,2015-04-12 21:07:04,2015-05-12 22:42:35,56,PRYMTRKRYXEZC,Direct,Opera,F,18,3757992063,0,3.757965e+09,3.758031e+09,China
129142,62132,2015-08-07 10:46:59,2015-08-27 22:35:23,36,XAZBVQEIGZMVM,Direct,Chrome,F,36,3758008198,0,3.757965e+09,3.758031e+09,China
129143,363333,2015-02-09 07:56:12,2015-03-19 16:55:29,37,LPFTNUDBBWDVD,SEO,FireFox,M,42,3758018545,0,3.757965e+09,3.758031e+09,China
129144,340800,2015-05-10 19:31:22,2015-05-15 09:27:33,9,VUDMWVCEHXMCV,Direct,Chrome,F,37,3758029146,0,3.757965e+09,3.758031e+09,China
129145,244330,2015-01-31 03:06:13,2015-05-23 11:23:39,18,MGGLMJDILUXKX,SEO,Safari,M,34,3758052531,0,3.758031e+09,3.758064e+09,China

In [37]:
ft.create_time_features(df)

AttributeError: module 'feature' has no attribute 'create_time_features'